# Generated by Django 5.1.3 on 2024-11-25 05:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('search_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin_location', models.CharField(max_length=50)),
                ('destination_location', models.CharField(max_length=50)),
                ('travel_class', models.CharField(choices=[('ECONOMY', 'ECONOMY'), ('PREMIUM_ECONOMY', 'PREMIUM_ECONOMY'), ('BUSINESS', 'BUSINESS'), ('FIRST', 'FIRST')], default='ECONOMY', max_length=50)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('last_search_at', models.DateTimeField(auto_now=True)),
                ('from_date', models.DateField()),
                ('is_one_way', models.BooleanField(default=False)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('direct_flight', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.userdata')),
            ],
        ),
    ]
