# Generated by Django 5.1.3 on 2024-12-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_searchhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao', models.CharField(max_length=10)),
                ('iata', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=5)),
                ('elevation', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('tz', models.CharField(max_length=255)),
            ],
        ),
    ]
